### ISSUE TITLE
USE_SYSTEM_zlib ....

### ISSUE THREAD

**Issue by eolivi** [openmeeg/OpenMEEG-project#4] opened 2015-01-11 11:03 UTC
I cannot USE_SYSTEM_zlib nor other packages proposed... Cmake is just looking for ZlibConfig.cmake, and is not even checking for zlib.h in /usr/include... Are'nt we missing a FindZlib.cmake file ?

**Comment by agramfort** [comment] 2015-01-11 16:15
@papadop ?

**Comment by papadop** [comment] 2015-02-26 18:41
That's related to the capitalization. Our subdir is named zlib so with USE_SYSTEM_ZLIB we execute find_package(zlib REQUIRED) instead of find_package(ZLIB REQUIRED)....
Corrected in a second by adding a zlib_find_package macro in zlib.cmake.

**Comment by papadop** [comment] 2015-02-26 18:49
Corrected with commit 20534f958c260fe5850baa555a385fa0f6ad028d.
Can you check and close this bug.

**Comment by eolivi** [comment] 2015-03-10 13:31
It looks OK for zlib, but not for HDF5 nor matio.
we could do the same for hdf5, because there is a file findHDF5.cmake in /usr/share/cmake-3.0/Modules,
But it looks like it doesn't work.
For matio, we need a findMatio.cmake no ? there are some on the web, I let you decide what is best.
(BTW does it work for you the use_external_* ??)

**Comment by papadop** [comment] 2015-03-17 21:24
Indeed... Of course, with cmake, the problem of finding packages is always complicated. hdf5 packages (at least in fedora do not provide the cmake config files and the generic one provided by cmake is less complete. matio is even worse. When we compile ours, we provide such a matio-config file but the standard matio itself does not provide one.... And the Findmatio.cmake we can find on the net are not compatible (cmake module vs config modes).

It should work now..

I hesitate to test such builds on ci as it would mean adding the packages on the machines which can bias the complete builds with all dependencies. Ore solution would be to duplicate the slaves but I'm kind of lazy. travis will test that...

**Comment by agramfort** [comment] 2015-03-17 21:37
thx @papadop

let's see if travis is happy.

https://github.com/openmeeg/openmeeg/pull/71

**Comment by agramfort** [comment] 2015-03-17 22:14
we're making progress

https://travis-ci.org/openmeeg/openmeeg/builds/54785751

now a pb with stable Matio I guess

**Comment by papadop** [comment] 2015-03-18 07:27
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 03/17/2015 11:14 PM, Alexandre Gramfort wrote:
> we're making progress
> 
> https://travis-ci.org/openmeeg/openmeeg/builds/54785751
> 
> now a pb with stable Matio I guess

Strange:
http://packages.ubuntu.com/fr/trusty/libdevel/libmatio-dev

Which version of ubuntu does travis use ???

	Theo.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlUJKO4ACgkQEr8WrU8nPV0U0wCcDN9oJRi/L+iHCsDU+H9s3X9N
4qIAnRxQSqtSdLjPCU+oigTOVCzpD7bs
=3oAt
-----END PGP SIGNATURE-----

**Comment by papadop** [comment] 2015-03-18 07:42
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 03/17/2015 11:14 PM, Alexandre Gramfort wrote:
> we're making progress
> 
> https://travis-ci.org/openmeeg/openmeeg/builds/54785751
> 
> now a pb with stable Matio I guess

Wrong version of matio:

Unpacking libmatio0 (from .../libmatio0_1.3.4-3_amd64.deb) ...

	THeo.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlUJLF4ACgkQEr8WrU8nPV0DNQCcC4GzWKfUSWasVllC1M7ermUZ
UJMAoKuhoT31yE4zYDDxPqmvNLmqPs9S
=OSL9
-----END PGP SIGNATURE-----

**Comment by agramfort** [comment] 2015-03-18 10:01
Can you clarify what the problem is?

**Comment by papadop** [comment] 2015-03-18 10:11
matio-1.3.4 vs matio 1.5.2 that is required...

Strange:
http://packages.ubuntu.com/fr/trusty/libdevel/libmatio-dev

Which version of ubuntu does travis use ???

**Comment by agramfort** [comment] 2015-03-18 10:26
No idea

Let me Google it

**Comment by agramfort** [comment] 2015-03-18 10:29
http://docs.travis-ci.com/user/ci-environment/

**Comment by papadop** [comment] 2015-03-18 10:54
Ouais. La 14.04 a deja un an.... Ils ne bougent quand meme pas tres vite chez travis (ce qui m'inquiete un peu c'est qu'ils parlent d'une migration plus que d'un ajout de fonctionnalite). Peut-etre peux tu essayer d'installer le paquet matio de la 14.04 (et le hdf5 concomitant probablement) pour essayer... Ca va peut-etre bloquer sur la glibc... mais pas sur. Sinon, il n'y a pas des packages sources sous debian/ubuntu ??

**Comment by agramfort** [comment] 2015-03-18 11:25
One year old is not a lot and I fear we may have the same pb on neurodebian. How much would it take to support the old version ? Or allow build without matio if installed version is too old?

**Comment by papadop** [comment] 2015-03-18 12:44
Well it's 20% of the life time !!! And the other version is 3 years old, which starts to be a lot....
It is impossible to support the old version of matio, period (unless someone is willing to do it, but IIRC there were bugs that were redhibitory) . We spent way too much time in supporting all configurations, it is just impossible to do everything.... Without matio is not a choice either bin formats come with lots of bugs, I'd rather suppress them as soon as possible (which may be in several years but only if we do not ship bin only releases which is done for about two releases if I'm not wrong).... The only possibility is to build with a static matio.

**Comment by papadop** [comment] 2015-03-18 13:54
Le's close this issue as soon as Manu has confirmed it works and open another one for compiling with a static matio.

**Comment by agramfort** [comment] 2015-03-18 14:57
ok @papadop fair enough.

Even more progress

https://s3.amazonaws.com/archive.travis-ci.org/jobs/54877637/log.txt
https://travis-ci.org/openmeeg/openmeeg/builds/54877636

now we have 10 failing tests but the code builds and 356 tests pass.

**Comment by papadop** [comment] 2015-03-18 16:19
Tests failing are expected:
See in the log:

CMake Warning at CMakeLists.txt:84 (message):
  OpenMEEG will not compile with matio versions less than 1.5.0.


CMake Warning at CMakeLists.txt:88 (message):
  OpenMEEG compiled without matio: this only generates ascii
  files which are big and can loose accuracy.  Comparison
  tests will not work in this situation.

And indeed only some comparison tests do not work...
Even though, it is not clear why 168 fails differently.
I suspect other comparisons are with text files.... which might not be good in terms of accuracy.
One possibility to solve this, rewrite the compare_matrix program with python and numpy....

The following tests FAILED:
	164 - cmp-HM-Head1 (OTHER_FAULT)
	165 - cmp-HMInv-Head1 (OTHER_FAULT)
	166 - cmp-SSM-Head1 (OTHER_FAULT)
	167 - cmp-DSM-Head1 (OTHER_FAULT)
	168 - cmp-H2EM-Head1 (Failed)
	169 - cmp-SurfGainEEG-Head1 (OTHER_FAULT)
	170 - cmp-ESTEEG-Head1 (OTHER_FAULT)
	171 - cmp-H2MM-Head1 (OTHER_FAULT)
	172 - cmp-SS2MM-Head1 (OTHER_FAULT)
	173 - cmp-SurfGainMEG-Head1 (OTHER_FAULT)

**Comment by agramfort** [comment] 2015-03-19 05:17
option 1:
find a way to install from source ... or find a .deb file that works on
travis...
option 2:
try to reactivate bin to see if it makes travis happy
option 3:
debug travis with a local VM...

I don't have much time to seriously look into it.

**Closed** 2015-03-19 17:35 UTC
